// Code generated by templ - DO NOT EDIT.
package http

func ValidateGenerated(value int) bool {
	if value == 1 {
		return true
	}
	if value == 2 {
		return true
	}
	if value == 3 {
		return true
	}
	if value == 4 {
		return true
	}
	if value == 5 {
		return true
	}
	if value == 6 {
		return true
	}
	if value == 7 {
		return true
	}
	return false
}
